lib/pointing_party/web/router.ex
defmodule PointingParty.Web.Router do
  use PointingParty.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PointingParty.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/join", JoinController, :join

    get "/new", PartyController, :new
    post "/create", PartyController, :create

    get "/signin", UserController, :signin
    post "/connect", UserController, :connect

    get "/show", PartyController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", PointingParty do
  #   pipe_through :api
  # end
end

lib/pointing_party_web/router.ex
defmodule PointingPartyWeb.Router do
  use PointingPartyWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", PointingPartyWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/join", JoinController, :join)

    get("/new", PartyController, :new)
    post("/create", PartyController, :create)

    get("/signin", UserController, :signin)
    post("/connect", UserController, :connect)

    get("/show", PartyController, :show)

    get("/:id", JoinController, :new)

    get("/.well-known/acme-challenge/:id", ChallengeController, :show)
  end

  # Other scopes may use custom stacks.
  # scope "/api", PointingPartyWeb do
  #   pipe_through :api
  # end
end

lib/pointing_party/web/controllers/party_controller.ex
defmodule PointingParty.PartyController do
  use PointingParty.Web, :controller

  plug :require_party when not action in [:create]
  plug :require_user when action in [:show]

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, %{"party" => %{"for" => ""}}) do
    conn
    |> put_flash(:info, "Please provide a session name")
    |> redirect(to: page_path(conn, :new))
  end
  def create(conn, %{"party" => %{"for" => party_name}}) do
    conn
    |> start_party_tracker(party_name)
    |> put_session(:party_name, party_name)
    |> redirect(to: user_path(conn, :signin))
  end

  def show(conn, _params) do
    conn
    |> assign(:party_key, get_session(conn, :party_key))
    |> assign(:party_name, get_session(conn, :party_name))
    |> assign(:user_name, get_session(conn, :user_name))
    |> render("show.html")
  end

  defp start_party_tracker(conn, party_name) do
    party_key = SecureRandom.urlsafe_base64
    PointingParty.PartyTracker.start_party(party_key, party_name)

    conn
    |> put_session(:party_key, party_key)
  end

  defp require_party(conn, _) do
    if party_key = get_session(conn, :party_key) do
      conn
      |> assign(:party_key, party_key)
      |> assign(:party_token, Phoenix.Token.sign(conn, "party token", party_key))
    else
      conn
      |> render("new.html")
      |> halt()
    end
  end
  defp require_user(conn, _) do
    if user_name = get_session(conn, :user_name) do
      conn
      |> assign(:user_name, user_name)
      |> assign(:user_token, Phoenix.Token.sign(conn, "user name", user_name))
    else
      conn
      |> render("signin.html")
      |> halt()
    end
  end
end

lib/pointing_party/web/views/party_view.ex
defmodule PointingParty.PartyView do
  use PointingParty.Web, :view
end

lib/pointing_party_web/controllers/party_controller.ex
defmodule PointingPartyWeb.PartyController do
  use PointingPartyWeb, :controller

  plug(:require_party when action not in [:create])
  plug(:require_user when action in [:show])

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"party" => %{"for" => ""}}) do
    conn
    |> put_flash(:info, "Please provide a session name")
    |> redirect(to: page_path(conn, :new))
  end

  def create(conn, %{"party" => %{"for" => party_name}}) do
    conn
    |> start_party_tracker(party_name)
    |> put_session(:party_name, party_name)
    |> redirect(to: user_path(conn, :signin))
  end

  def show(conn, _params) do
    conn
    |> assign(:party_key, get_session(conn, :party_key))
    |> assign(:party_name, get_session(conn, :party_name))
    |> assign(:user_name, get_session(conn, :user_name))
    |> render("show.html")
  end

  defp start_party_tracker(conn, party_name) do
    party_key = PointingParty.PartyTracker.start_party(party_name)

    conn
    |> put_session(:party_key, party_key)
  end

  defp require_party(conn, _) do
    if party_key = get_session(conn, :party_key) do
      conn
      |> assign(:party_key, party_key)
      |> assign(:party_token, Phoenix.Token.sign(conn, "party token", party_key))
    else
      conn
      |> render("new.html")
      |> halt()
    end
  end

  defp require_user(conn, _) do
    if user_name = get_session(conn, :user_name) do
      conn
      |> assign(:user_name, user_name)
      |> assign(:user_token, Phoenix.Token.sign(conn, "user name", user_name))
    else
      conn
      |> render("signin.html")
      |> halt()
    end
  end
end

lib/pointing_party_web/views/party_view.ex
defmodule PointingPartyWeb.PartyView do
  use PointingPartyWeb, :view
end

lib/pointing_party_web/templates/party/new.html.eex
Start a new session
<%= form_for @conn, party_path(@conn, :create), [as: :party, class: "form-inline"], fn f -> %>
  <%= text_input f, :for, class: "form-control" %>
  <%= submit "Create", class: "btn btn-primary" %>
<% end %>

lib/pointing_party_web/templates/party/show.html.eex
<div class="row">
  <div class="col-sm-12">
    <h2><%= @party_name %></h2>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <input class="btn btn-primary btn-points" type="button" data-points="0" value="0">
    <input class="btn btn-primary btn-points" type="button" data-points="1" value="1">
    <input class="btn btn-primary btn-points" type="button" data-points="2" value="2">
    <input class="btn btn-primary btn-points" type="button" data-points="3" value="3">
    <input class="btn btn-primary btn-points" type="button" data-points="5" value="5">
    <input class="btn btn-primary btn-points" type="button" data-points="8" value="8">
    <input class="btn btn-primary btn-points" type="button" data-points="?" value="?">
  </div>
  <div class="col-md-4">
    <input class="btn btn-info" id="btn-clear" type="button" value="Clear">
    <input class="btn btn-info" id="btn-show" type="button" value="Show votes">
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <input class="copy-link party-link" id="party-link" type="text" readonly value="<%=join_url(@conn, :new, assigns[:party_key])%>"><span class="copy-link clipboard" data-target="party-link">📋</span>
  </div>
</div>
<div class="row">
  <div class="col-sm-7">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Users</h3>
      </div>
      <div id="users" class="panel-body list-group">
      </div>
    </div>
  </div>
  <div class="col-sm-1">
  </div>
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Chat</h3>
      </div>
      <div id="messages" class="panel-body">
      </div>
      <div class="panel-footer">
        <input id="message-input"
               class="form-control"
               type="text"
               placeholder="Send..."/>
      </div>
    </div>
  </div>
</div>
<script>
  /*
    TODO: eventually some of this stuff will be in a ETS table can be
          looked up by a "user key" or something, to make this more
          secure and easier to enhance */
  window.partyName = "<%= assigns[:party_name] %>";
  window.partyKey = "<%= assigns[:party_key] %>";
  window.userName = "<%= assigns[:user_name] %>";
  window.userToken = "<%= assigns[:user_token] %>";
</script>